
image: docker:19.03.7
services:
  - docker:19.03.7-dind
stages:
  - Build
  - Push

##############################################################################
##                              Variables                                   ##
##############################################################################
variables:
  AWS_ROLE_ARN: arn:aws:iam::167259143853:role/gitlab-ci
  AWS_WEB_IDENTITY_TOKEN_FILE: /tmp/web-identity-token


##############################################################################
##                Setup OIDC Assume Role Template                          ##
##############################################################################
.assume_role: &assume_role
  before_script:
    - apk add python3
    - pip3 install awscli
    - >
      export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
      $(aws sts assume-role-with-web-identity
      --role-arn $AWS_ROLE_ARN
      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
      --web-identity-token $CI_JOB_JWT_V2
      --duration-seconds 3600
      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
      --output text))
    - aws sts get-caller-identity
    - $(aws ecr get-login --no-include-email --region eu-west-1)

##############################################################################
##                             Build Image                                 ##
##############################################################################
Build:
  image: docker:19.03.5
  services:
    - docker:19.03.5-dind
  <<: *assume_role
  stage: Build
  script:
    - docker build --compress -t $ECR_REPO:$CI_COMMIT_SHORT_SHA .
    - docker push $ECR_REPO:$CI_COMMIT_SHORT_SHA

##############################################################################
##                       Push to ECR                                       ##
##############################################################################
Push:
  image: docker:19.03.5
  services:
    - docker:19.03.5-dind
  stage: Push
  <<: *assume_role
  script:
    - docker pull $ECR_REPO:$CI_COMMIT_SHORT_SHA
    - docker tag $ECR_REPO:$CI_COMMIT_SHORT_SHA $ECR_REPO:latest
    - docker push $ECR_REPO:latest
