name: Trivy and Cosign Image Security - Docker HUB

on:
  push:
    branches:
      - main
    
env:
  IMAGE_NAME: nginxwebserver

# cancel outdated jobs for the same reference
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      matrix:
        include:
        - arch    : amd64
          mode    : build-and-test
        - arch    : arm64
          variant : v8
          mode    : build-only
    env:
      PLATFORM  : linux/${{ matrix.arch }}${{ (matrix.variant != '' && format('/{0}', matrix.variant)) || '' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Log into registry
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:${{ github.run_id }}
      
      - name: cosign-installer
        uses: sigstore/cosign-installer@v2.0.0
        
      - name: Write signing key to disk
        run: 'echo "$PRIVATE_KEY" > cosign.key'
        shell: bash
        env:
          PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      
      - name: Sign the published Docker image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: cosign sign --key cosign.key -a "author=CalvineDevOps" ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:${{ github.run_id }}
