name: Trivy and Cosign Image Security

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: nginxwebserver
  GITHUB_ACTOR: nyaras ### my github username is uppercase ☹️ so I have to set this

jobs:
  build:
    strategy:
      matrix:
        include:
        - arch    : amd64
          mode    : build-and-test
        - arch    : arm64
          variant : v8
          mode    : build-only
    runs-on: ubuntu-latest
    env:
      VOLUME    : osm-db
      CONTAINER : osm-www
      MOUNT     : /data/database/
      PLATFORM  : linux/${{ matrix.arch }}${{ (matrix.variant != '' && format('/{0}', matrix.variant)) || '' }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        # with:
        #   platforms: 'arm64,arm'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry
        uses: docker/login-action@v1.12.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.GITHUB_ACTOR }}/${{ env.IMAGE_NAME }}:unsignednotsecure
          platforms  : ${{ env.PLATFORM }}
          cache-from : type=gha,scope=${{ github.workflow }}:${{ env.PLATFORM }}
          cache-to   : type=gha,scope=${{ github.workflow }}:${{ env.PLATFORM }},mode=max

      # - name: cosign-installer
      #   uses: sigstore/cosign-installer@v2.0.0
        
      # - name: Write signing key to disk
      #   run: 'echo "$PRIVATE_KEY" > cosign.key'
      #   shell: bash
      #   env:
      #     PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      
      # - name: Sign the published Docker image
      #   env:
      #     COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      #   run: cosign sign --key cosign.key -a "author=CalvineDevOps" ${{ env.REGISTRY }}/${{ env.GITHUB_ACTOR }}/${{ env.IMAGE_NAME }}:${{ github.run_id }}
